### ISSUE TITLE
[ModGen] Be able do disable identity on PKs

### ISSUE THREAD

**Issue by c3dr0x** [KleeGroup/kinetix-tools#2]
When we synchronize referential table from an external system, we should be able to keep the PK value of the external system. So disable the `identity` mention in SQLServer.

**Comment by JabX** [comment]
I am not convinced that it is a good idea to use some other system's IDs as our own IDs in our database. If the ID has a meaning in that case it is a "Code" and is stored as a varchar, which guarantees that it's not an identity column and that I can safely use it as an unique identifier for my object. Otherwise, it would be best to store it in as other column as "ExtSystemId" or something.

The main grievance I have with allowing this is that it will certainly be abused by some people who clearly can't make the difference between a Code and an Id (and I know some), and it will break the general immutable rule of "Id = autogenerated, Code = static reference", which is a basic rule that is easy to follow.

In your case, if you can trust the external ID to be a unique identifier that you want to use just like you would use a static reference list, store it as a Code and do the parsing when you need to interact.

**Comment by c3dr0x** [comment]
Alright that makes sens, I'll do that.
